#!/usr/bin/env python3
from src.tunnels import Tunnels
import sys

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] == "--help":
        print("Usage: pytunnels <config_file>")
        sys.exit(0)
    Tunnels(sys.argv[1])
